"""Add is_authorized field to Guardian

Generated by assistant
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
