# Generated by Django 5.1.6 on 2025-11-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0003_guardianapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianapproval',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
