# Generated by Django 5.1.6 on 2025-11-24 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0004_alter_guardianapproval_id'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardianapproval',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='guardianapproval',
            name='acted_by',
        ),
        migrations.CreateModel(
            name='UnregisteredGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, help_text='Guardian photo', null=True, upload_to='unregisteredguardian_photos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='teacher.teacherprofile')),
            ],
            options={
                'verbose_name': 'Unregistered Guardian',
                'verbose_name_plural': 'Unregistered Guardians',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='GuardianApproval',
        ),
    ]
