# Generated by Django 5.1.6 on 2025-11-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0005_remove_guardianapproval_guardian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregisteredguardian',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allowed', 'Allowed'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
