# Generated by Django 5.1.6 on 2025-11-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0007_guardian_delete_unregisteredguardian'),
        ('parents', '0010_parentevent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='parent_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_guardians', to='parents.parentguardian'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='parents.student'),
        ),
    ]
