# Generated by Django 5.1.6 on 2025-11-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentguardian',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
