# Generated by Django 5.1.6 on 2025-11-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_parentguardian_password_parentguardian_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('attendance', 'Attendance'), ('pickup', 'Pickup'), ('event', 'Event'), ('other', 'Other')], default='other', max_length=32)),
                ('message', models.TextField()),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='parents.parentguardian')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='parents.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
