# Generated by Django 5.1.6 on 2025-11-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_parentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentguardian',
            name='must_change_credentials',
            field=models.BooleanField(default=False),
        ),
    ]
