# Generated by Django 5.1.6 on 2025-11-21 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0008_populate_scheduled_at'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parents_mobileregistration',
            },
        ),
        migrations.AddField(
            model_name='parentevent',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='teacher.teacherprofile'),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='parent_avatars/'),
        ),
        migrations.AlterField(
            model_name='parentevent',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parentevent',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentevent',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='parentevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='parents.parentguardian'),
        ),
        migrations.AlterField(
            model_name='parentevent',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ParentMobileAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_account', to='parents.parentguardian')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_mobile_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Mobile Account',
                'verbose_name_plural': 'Parent Mobile Accounts',
            },
        ),
    ]
