# Generated by Django 5.1.6 on 2025-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0009_mobileregistration_parentevent_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentevent',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
