# Generated by Django 5.1.6 on 2025-11-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0010_parentevent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentnotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
