# Generated by Django 5.1.6 on 2025-12-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0011_parentnotification_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentnotification',
            name='read',
        ),
    ]
