# Generated by Django 5.1.6 on 2025-12-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='transaction_type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('drop-off', 'Drop-off'), ('pick-up', 'Pick-up')], default='attendance', help_text='Type of transaction: regular attendance, drop-off, or pick-up', max_length=20),
        ),
    ]
